name: Coverage

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
