name: Coverage

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          env: "add4c20f-d619-41cb-9044-b275f22ea7eb"
