name: Coverage

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true
  workflow_dispatch:

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
	  verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
	  verbose: true
