name: Upload coverage reports to Codecov

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: codecov/codecov-action@v3.1.3
      name: Codecov
      
      with:
        token: add4c20f-d619-41cb-9044-b275f22ea7eb
